# -*- coding: utf-8 -*-
"""Text_Extraction_From_Images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2SaPjqljrkbVcRTFzuPeE6rkL6G5ZmX
"""

import numpy as np
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from scipy.linalg import svd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder,LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report 
from sklearn import datasets
import random
from collections import defaultdict
from scipy.sparse import csr_matrix,hstack
from sklearn.utils import shuffle
from sklearn.metrics import calinski_harabasz_score
from sklearn.decomposition import TruncatedSVD
import seaborn as sns
import cv2
drive.mount('/content/drive/',force_remount=True)
!ls "/content/drive/My Drive"

!sudo apt install tesseract-ocr
!pip install pytesseract

path1='/content/drive/My Drive/MASTERS PROJECT/Data Administration/Screenshot 2021-07-05 at 6.27.33 PM.png'
path2='/content/drive/My Drive/MASTERS PROJECT/Data Administration/Screenshot 2021-07-05 at 6.26.47 PM.png'
#Load the flights.csv file
img1 = cv2.imread(path1) 
img2= cv2.imread(path2) 
# Output img with window name as 'image'
dim=(500,500)
from google.colab.patches import cv2_imshow 
#img1 = cv2.resize(img1, dim, interpolation = cv2.INTER_AREA)
#img2 = cv2.resize(img2, dim, interpolation = cv2.INTER_AREA)
cv2_imshow(img1) 
cv2_imshow(img2) 
#img1=cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
#img2=cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

import pytesseract
from pytesseract import image_to_string
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

#pytesseract.pytesseract.tesseract_cmd = '/usr/local/lib/python3.7/dist-packages'
extractedInformation = pytesseract.image_to_string(img1)
cv2_imshow(img1)
print('---------------------------------------------') 
print(extractedInformation)
print('---------------------------------------------') 
extractedInformation = pytesseract.image_to_string(img2)
cv2_imshow(img2)
print('---------------------------------------------') 
print(extractedInformation)